# Sample configuration for the tutorial
# has 3 scrappers: falco, node and docker
global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
        monitor: 'nunez-family-monitor'

scrape_configs:
  - job_name: 'falco-exporter'
    static_configs:
      - targets: ['192.168.1.16:9376']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.16:9100', 'raspberrypi.home:9100', 'dmaf5:9100']
  - job_name: 'docker-exporter'
    static_configs:
      - targets: ['192.168.1.16:9323', 'raspberrypi.home:9323', 'dmaf5:9323']
  
    tls_config:
      insecure_skip_verify: true
